---
deployment:
  tasks:
    - export DEPLOYPATH=/home/deaaupyx/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH